// frontend/src/components/PlaceRouteCard.svelte
<script lang="ts">
  import type { ApiRoute } from '../lib/types';
  import { formatSchedule, routePath, safeText, withUnit } from '../lib/formatters';
  import CompanyInfo from './CompanyInfo.svelte';
  import MetricsGrid from './MetricsGrid.svelte';
  import RouteHeader from './RouteHeader.svelte';

  export let route: ApiRoute;

  $: metrics = [
    ['📍', 'Pasa por', safeText(route.punto)],
    ['🧭', 'Recorrido', routePath(route)],
    ['🕐', 'Horario', formatSchedule(route)],
    ['🔄', 'Frecuencia', withUnit(route.frecuencia_min, 'min', 'Cada ')]
  ] as Array<[string, string, string]>;
</script>

<article class="ruta-card ruta-lugar-card">
  <RouteHeader {route} showNext={false} />
  <CompanyInfo {route} />
  <MetricsGrid {metrics} />
</article>

// frontend/src/components/PlaceRouteCard.tsx
import type { ApiRoute } from '../api/types';
import { formatSchedule, routePath, safeText, withUnit } from '../lib/formatters';
import { CompanyInfo } from './CompanyInfo';
import { MetricsGrid } from './MetricsGrid';
import { RouteHeader } from './RouteHeader';

export type PlaceRouteCardProps = {
  route: ApiRoute;
};

export function PlaceRouteCard({ route }: PlaceRouteCardProps) {
  const metrics: Array<[string, string, string]> = [
    ['📍', 'Pasa por', safeText(route.punto)],
    ['🧭', 'Recorrido', routePath(route)],
    ['🕐', 'Horario', formatSchedule(route)],
    ['🔄', 'Frecuencia', withUnit(route.frecuencia_min, 'min', 'Cada ')]
  ];

  return (
    <article className="ruta-card ruta-lugar-card">
      <RouteHeader route={route} showNext={false} />
      <CompanyInfo route={route} />
      <MetricsGrid metrics={metrics} />
    </article>
  );
}
