// frontend/src/components/RouteHeader.tsx
import type { ApiRoute } from '../api/types';
import { routeCode, routeDirection, withUnit } from '../lib/formatters';

export type RouteHeaderProps = {
  route: ApiRoute;
  showNext?: boolean;
};

export function RouteHeader({ route, showNext = true }: RouteHeaderProps) {
  const code = routeCode(route);
  const direction = routeDirection(route);
  const next = showNext
    ? withUnit(route.proximo_paso_min ?? route.proxima_unidad?.minutos_restantes, 'min', '~')
    : '';
  const directionIcon = direction === 'IDA' ? '→ ' : direction === 'VUELTA' ? '← ' : '';

  return (
    <div className="ruta-card-header">
      <div className="ruta-identidad">
        <span className="badge-ruta">{code}</span>
        {direction && (
          <span className="badge-sentido" data-sentido={direction}>
            {directionIcon}
            {direction}
          </span>
        )}
      </div>
      {next && (
        <div className="proxima-unidad">
          <span>Salida desde inicio</span>
          <strong>{next}</strong>
        </div>
      )}
    </div>
  );
}

// frontend/src/components/RouteHeader.svelte
<script lang="ts">
  import type { ApiRoute } from '../lib/types';
  import { routeCode, routeDirection, withUnit } from '../lib/formatters';

  export let route: ApiRoute;
  export let showNext = true;

  $: code = routeCode(route);
  $: direction = routeDirection(route);
  $: next = showNext ? withUnit(route.proximo_paso_min, 'min', '~') : '';
  $: directionIcon = direction === 'IDA' ? '→ ' : direction === 'VUELTA' ? '← ' : '';
</script>

<div class="ruta-card-header">
  <div class="ruta-identidad">
    <span class="badge-ruta">{code}</span>
    {#if direction}
      <span class="badge-sentido" data-sentido={direction}>{directionIcon}{direction}</span>
    {/if}
  </div>
  {#if next}
    <div class="proxima-unidad">
      <span>Salida desde inicio</span>
      <strong>{next}</strong>
    </div>
  {/if}
</div>
